#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${1:-.env.enterprise}"

if [[ -f "${ENV_FILE}" ]]; then
  echo "Refusing to overwrite existing ${ENV_FILE}"
  exit 1
fi

gen_secret() {
  openssl rand -hex 24
}

cat > "${ENV_FILE}" <<EOF
# Enterprise baseline generated by scripts/enterprise-bootstrap.sh
RM_PORT=3000
RM_DB_PATH=/data/reflect-memory.db
RM_DEPLOYMENT_MODE=self-host
RM_TENANT_ID=tenant-$(date +%s)
RM_API_KEY=rm_enterprise_$(gen_secret)
RM_MODEL_NAME=gpt-4o-mini
RM_MODEL_API_KEY=
RM_MODEL_BASE_URL=http://internal-llm-gateway.local/v1
RM_CHAT_OPENAI_BASE_URL=http://internal-llm-gateway.local/v1
RM_DISABLE_MODEL_EGRESS=true
RM_REQUIRE_INTERNAL_MODEL_BASE_URL=true
RM_ALLOW_PUBLIC_WEBHOOKS=false
RM_ALLOWED_MODEL_HOSTS=internal-llm-gateway.local
RM_DASHBOARD_SERVICE_KEY=svc_$(gen_secret)
RM_DASHBOARD_JWT_SECRET=$(gen_secret)
RM_OWNER_EMAIL=
RM_SSO_ENABLED=false
RM_SSO_JWKS_URL=
RM_SSO_ISSUER=
RM_SSO_AUDIENCE=
RM_SSO_EMAIL_CLAIM=email
EOF

echo "Wrote ${ENV_FILE}"
echo "Next steps:"
echo "  1) Fill RM_OWNER_EMAIL and model provider settings"
echo "  2) Validate: node scripts/validate-enterprise-env.mjs ${ENV_FILE}"
echo "  3) Start: docker compose --env-file ${ENV_FILE} --profile self-host up --build"
